###
# This file is example of configuration that must be placed near the built jar
###
mongo:
  host: 192.168.1.3
  port: 27017
  db: jagpb
  auth:
    user: jagpb
    password: jagpb123
    authBase: admin